#!/usr/bin/env bash

# exit when a command fails
set -o errexit


TEXFILE=main

rm -f *.aux *.bbl *.blg *.brf *.log *.out *.toc

pdflatex ${TEXFILE}
bibtex ${TEXFILE}
pdflatex ${TEXFILE}
pdflatex ${TEXFILE}


rm -f *.aux *.bbl *.blg *.brf *.log *.out *.toc
